### ISSUE TITLE
Random HTTP Rate Limits

### ISSUE THREAD

**Issue by wSedlacek** [autero1/action-terragrunt#68]
I have noticed that every so often I get rate limits when using this action.
It appears to be because GitHub has rate limits by IP and when using the public runners the IPs for all runs get grouped together.
I believe if we changed this URL to something that wasn't on GitHub then the issue would be resolved.
https://github.com/autero1/action-terragrunt/blob/881cdfc8f21fac41aaca512c3d1d66fed3e1da94/src/action.ts#L12

setup-go had the same issue and that is what solution they went with
https://github.com/actions/setup-go/pull/20

**Comment by DanielViglione** [comment]
Ironically, I was just digging into the source code myself. I am also getting the rate limit errors by the Github API. And you are right when using the public runners, the IPs of all the runners get grouped together. I believe the error is being raised here:

```
  const octokit = new Octokit();

  const latestRelease = await octokit.repos.getLatestRelease({
    owner: 'gruntwork-io',
    repo: 'terragrunt'
  });
```

Notice the Octokit constructor is not taking in any arguments. If you look on the docs: https://octokit.github.io/rest.js/v18, you can specify an auth, which can be a Personal access token. That would resolve the issue. Because you pass in the PAT through the action and you will not have any rate limits. 

And I also believe the error happens at this point, because notice the "Latest Terragrunt version:" in the action source code here: https://github.com/autero1/action-terragrunt/blob/881cdfc8f21fac41aaca512c3d1d66fed3e1da94/src/action.ts#L88 never gets printed indicating its failing at  octokit.repos.getLatestRelease. 

All in all, the action should accept a PAT as an argument:

```
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest
          token: ${{ secrets.GH_PAT }}
```

which then gets passed into the action and the action should pass it into the auth of the Octokit constructor.

**Comment by ThomasAribart** [comment]
Hi ! Having the same pb on my project :)
